# Generated by Django 3.2.10 on 2022-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('pv', models.IntegerField(null=True)),
            ],
        ),
    ]
