# Generated by Django 3.2.10 on 2022-03-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugfav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favdrugs',
            name='favduration',
        ),
        migrations.RemoveField(
            model_name='favdrugs',
            name='favfrequency',
        ),
        migrations.RemoveField(
            model_name='favdrugs',
            name='favinstructions',
        ),
        migrations.RemoveField(
            model_name='favdrugs',
            name='favnoofdays',
        ),
    ]
