# Generated by Django 3.2.10 on 2022-03-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugfav', '0002_auto_20220309_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favdrugs',
            name='favdosageform',
        ),
    ]
