# Generated by Django 3.2.10 on 2022-03-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('assistant_id', models.AutoField(primary_key=True, serialize=False)),
                ('assistant_name', models.CharField(max_length=200)),
                ('assistant_gender', models.CharField(max_length=20)),
                ('assistant_email', models.EmailField(max_length=100)),
                ('assistant_age', models.IntegerField()),
                ('patient_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(max_length=200)),
                ('clinic_address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_gender', models.CharField(max_length=20)),
                ('doctor_email', models.EmailField(max_length=100)),
                ('doctor_age', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_gender', models.CharField(max_length=20)),
                ('current_disease', models.CharField(max_length=1000)),
                ('patient_email', models.EmailField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_address', models.CharField(max_length=500)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assistant')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('surgery_id', models.AutoField(primary_key=True, serialize=False)),
                ('surgery_name', models.CharField(max_length=100)),
                ('surgery_price', models.IntegerField()),
                ('surgery_description', models.CharField(max_length=100)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('drug_dose', models.CharField(max_length=100)),
                ('drug_dosage_form', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('number_of_days', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=500)),
                ('patient_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=100)),
                ('material_price', models.IntegerField()),
                ('material_usage', models.CharField(max_length=200)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('Lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lab_name', models.CharField(max_length=100)),
                ('Lab_type', models.CharField(max_length=50)),
                ('patient_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_Phone',
            fields=[
                ('clinic_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinic_phone', models.CharField(max_length=100)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('checkup_type', models.CharField(max_length=25)),
                ('patient_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
    ]
