# Generated by Django 3.2.10 on 2022-03-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavLabs',
            fields=[
                ('Lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('Lab_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavScans',
            fields=[
                ('Scan_id', models.AutoField(primary_key=True, serialize=False)),
                ('Scan_name', models.CharField(max_length=100)),
            ],
        ),
    ]
